// Created by Crowbar 0.74

$modelname "vgui\UI_arenadoor01.mdl"

$bodygroup "Body"
{
	studio "UI_arenadoor01_reference.smd"
}
$bodygroup "randomlight"
{
	blank
	studio "UI_team01_random_lightbodygroup.smd"
}


$surfaceprop "default"

$contents "solid"

$illumposition -24.855 0.032 33.48

$mostlyopaque

$cdmaterials "vgui\replay\thumbnails\models\"

$cbox 0 0 0 0 0 0

$bbox -6.063 -54.986 0 6 5.276 66.959

$definebone "base" "" 0 0 0 0 0 89.999982 0 0 0 0 0 0
$definebone "doorhinge" "base" -46.661724 31.972027 -5.996205 0 0 0 0 0 0 0 0 0
$definebone "doorhandle" "doorhinge" 18.079386 -2.476408 1.115959 0 0 0 0 0 0 0 0 0
$definebone "light1" "base" 5.276351 42.659306 6 0 0 0 0 0 0 0 0 0


$sequence "idle" {
	"ui_arenadoor01_anims\idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "hoveropen" {
	"ui_arenadoor01_anims\hoveropen.smd"
	{ event AE_CL_BODYGROUP_SET_VALUE 1 "randomlight 1" }
	{ event AE_CL_PLAYSOUND 1 "Door.Open" }
	fadein 0.2
	fadeout 0.2
	fps 65
}

$sequence "hoverclose" {
	"ui_arenadoor01_anims\hoverclose.smd"
	{ event AE_CL_BODYGROUP_SET_VALUE 5 "randomlight 0" }
	{ event AE_CL_PLAYSOUND 1 "Door.Close" }
	fadein 0.2
	fadeout 0.2
	fps 35
}
